/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://sdplx3sp35gftllopklr7n67xm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vnewprcnfba2xadq45h6gq6iea",
    "aws_cognito_identity_pool_id": "us-east-1:41cc09ce-8106-4e9b-944b-c421cdc79e92",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CLsEnyqWW",
    "aws_user_pools_web_client_id": "6df73198vmvi5dsa9366fivn1j",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "lozzby-storage-339a6f4c64856-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
